"""initial

Revision ID: 0001
Revises:
Create Date: 2026-07-21 16:21:03.183899
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TENANT_TABLES = (
    'action_deliveries', 'actions', 'artifacts', 'audit_entries', 'changes',
    'devices', 'events', 'hook_credentials', 'hosts', 'memberships',
    'relay_outbox', 'repair_candidates', 'repairs', 'repositories', 'sessions',
    'signing_keys', 'stream_tickets', 'users', 'verification_results', 'verifications',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('CREATE SEQUENCE events_cloud_ingest_seq_seq START WITH 1')
    op.create_table('tenants',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('external_subject', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_subject')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=256), nullable=False),
    sa.Column('encryption_metadata', sa.JSON(), nullable=False),
    sa.Column('retention_class', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'object_key')
    )
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('actor_id', sa.String(length=512), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('target_kind', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=512), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('before_state_hash', sa.String(length=128), nullable=True),
    sa.Column('after_state_hash', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('actor_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_tenant_id'), 'audit_entries', ['tenant_id'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('key_id', sa.String(length=256), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key_id')
    )
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('hosts',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('public_key_algorithm', sa.String(length=32), nullable=False),
    sa.Column('health_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adapter_version', sa.String(length=128), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_tenant_id'), 'hosts', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('signing_keys',
    sa.Column('key_id', sa.String(length=256), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key_ref', sa.String(length=2048), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('activates_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key_id')
    )
    op.create_index(op.f('ix_signing_keys_tenant_id'), 'signing_keys', ['tenant_id'], unique=False)
    op.create_table('actions',
    sa.Column('action_id', sa.String(length=256), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_by_device_id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('parameters_hash', sa.String(length=128), nullable=False),
    sa.Column('expected_state_version', sa.BigInteger(), nullable=False),
    sa.Column('expected_state_hash', sa.String(length=128), nullable=False),
    sa.Column('nonce_hash', sa.LargeBinary(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('device_key_id', sa.String(length=256), nullable=False),
    sa.Column('device_algorithm', sa.String(length=32), nullable=False),
    sa.Column('device_signature', sa.Text(), nullable=False),
    sa.Column('cloud_key_id', sa.String(length=256), nullable=False),
    sa.Column('cloud_algorithm', sa.String(length=32), nullable=False),
    sa.Column('cloud_signature', sa.Text(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('audit_entry_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audit_entry_id'], ['audit_entries.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'action_id')
    )
    op.create_index(op.f('ix_actions_tenant_id'), 'actions', ['tenant_id'], unique=False)
    op.create_table('repositories',
    sa.Column('host_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('canonical_identity', sa.String(length=512), nullable=False),
    sa.Column('repository_handle', sa.String(length=256), nullable=False),
    sa.Column('relay_scopes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_identity'),
    sa.UniqueConstraint('tenant_id', 'repository_handle')
    )
    op.create_index(op.f('ix_repositories_host_id'), 'repositories', ['host_id'], unique=False)
    op.create_index(op.f('ix_repositories_tenant_id'), 'repositories', ['tenant_id'], unique=False)
    op.create_table('action_deliveries',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'action_id', 'attempt')
    )
    op.create_index(op.f('ix_action_deliveries_tenant_id'), 'action_deliveries', ['tenant_id'], unique=False)
    op.create_table('hook_credentials',
    sa.Column('key_id', sa.String(length=256), nullable=False),
    sa.Column('secret_hash', sa.LargeBinary(length=64), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key_id')
    )
    op.create_index(op.f('ix_hook_credentials_repository_id'), 'hook_credentials', ['repository_id'], unique=False)
    op.create_index(op.f('ix_hook_credentials_tenant_id'), 'hook_credentials', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('local_session_id', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('state_version', sa.BigInteger(), nullable=False),
    sa.Column('state_hash', sa.String(length=128), nullable=False),
    sa.Column('next_session_seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'host_id', 'local_session_id')
    )
    op.create_index(op.f('ix_sessions_host_id'), 'sessions', ['host_id'], unique=False)
    op.create_index(op.f('ix_sessions_repository_id'), 'sessions', ['repository_id'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_table('changes',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('path_hash', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changes_repository_id'), 'changes', ['repository_id'], unique=False)
    op.create_index(op.f('ix_changes_session_id'), 'changes', ['session_id'], unique=False)
    op.create_index(op.f('ix_changes_tenant_id'), 'changes', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=256), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('cloud_ingest_seq', sa.BigInteger(), nullable=False),
    sa.Column('session_seq', sa.BigInteger(), nullable=False),
    sa.Column('local_log_seq', sa.BigInteger(), nullable=True),
    sa.Column('repo_seq', sa.BigInteger(), nullable=True),
    sa.Column('client_stream_seq', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_ingest_seq'),
    sa.UniqueConstraint('tenant_id', 'event_id'),
    sa.UniqueConstraint('tenant_id', 'session_id', 'session_seq')
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index('ix_events_session_replay', 'events', ['tenant_id', 'session_id', 'session_seq'], unique=False)
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('stream_tickets',
    sa.Column('ticket_hash', sa.LargeBinary(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=512), nullable=False),
    sa.Column('after_session_seq', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ticket_hash')
    )
    op.create_index(op.f('ix_stream_tickets_session_id'), 'stream_tickets', ['session_id'], unique=False)
    op.create_index(op.f('ix_stream_tickets_tenant_id'), 'stream_tickets', ['tenant_id'], unique=False)
    op.create_table('verifications',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('contract_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_repository_id'), 'verifications', ['repository_id'], unique=False)
    op.create_index(op.f('ix_verifications_session_id'), 'verifications', ['session_id'], unique=False)
    op.create_index(op.f('ix_verifications_tenant_id'), 'verifications', ['tenant_id'], unique=False)
    op.create_table('relay_outbox',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('cloud_ingest_seq', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_id')
    )
    op.create_index(op.f('ix_relay_outbox_session_id'), 'relay_outbox', ['session_id'], unique=False)
    op.create_index(op.f('ix_relay_outbox_tenant_id'), 'relay_outbox', ['tenant_id'], unique=False)
    op.create_table('repairs',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('verification_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('failure_fingerprint', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repairs_repository_id'), 'repairs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repairs_tenant_id'), 'repairs', ['tenant_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('evidence_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'verification_id', 'check_id')
    )
    op.create_index(op.f('ix_verification_results_tenant_id'), 'verification_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_verification_results_verification_id'), 'verification_results', ['verification_id'], unique=False)
    op.create_table('repair_candidates',
    sa.Column('repair_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('patch_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('proof_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patch_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['proof_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['repair_id'], ['repairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_candidates_tenant_id'), 'repair_candidates', ['tenant_id'], unique=False)
    _enable_row_level_security()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP TRIGGER IF EXISTS audit_entries_append_only ON "audit_entries"')
        op.execute('DROP FUNCTION IF EXISTS reject_audit_mutation()')
    op.drop_index(op.f('ix_repair_candidates_tenant_id'), table_name='repair_candidates')
    op.drop_table('repair_candidates')
    op.drop_index(op.f('ix_verification_results_verification_id'), table_name='verification_results')
    op.drop_index(op.f('ix_verification_results_tenant_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_repairs_tenant_id'), table_name='repairs')
    op.drop_index(op.f('ix_repairs_repository_id'), table_name='repairs')
    op.drop_table('repairs')
    op.drop_index(op.f('ix_relay_outbox_tenant_id'), table_name='relay_outbox')
    op.drop_index(op.f('ix_relay_outbox_session_id'), table_name='relay_outbox')
    op.drop_table('relay_outbox')
    op.drop_index(op.f('ix_verifications_tenant_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_session_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_repository_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_stream_tickets_tenant_id'), table_name='stream_tickets')
    op.drop_index(op.f('ix_stream_tickets_session_id'), table_name='stream_tickets')
    op.drop_table('stream_tickets')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_index('ix_events_session_replay', table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_changes_tenant_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_session_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_repository_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_repository_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_host_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_hook_credentials_tenant_id'), table_name='hook_credentials')
    op.drop_index(op.f('ix_hook_credentials_repository_id'), table_name='hook_credentials')
    op.drop_table('hook_credentials')
    op.drop_index(op.f('ix_action_deliveries_tenant_id'), table_name='action_deliveries')
    op.drop_table('action_deliveries')
    op.drop_index(op.f('ix_repositories_tenant_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_host_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_actions_tenant_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_signing_keys_tenant_id'), table_name='signing_keys')
    op.drop_table('signing_keys')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_hosts_tenant_id'), table_name='hosts')
    op.drop_table('hosts')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_entries_tenant_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_artifacts_tenant_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP SEQUENCE events_cloud_ingest_seq_seq')
    # ### end Alembic commands ###


def _enable_row_level_security() -> None:
    if op.get_bind().dialect.name != 'postgresql':
        return
    tenant_setting = "NULLIF(current_setting('app.tenant_id', true), '')::uuid"
    for table in TENANT_TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table}" '
            f'USING (tenant_id = {tenant_setting}) '
            f'WITH CHECK (tenant_id = {tenant_setting})'
        )
    op.execute('ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE "tenants" FORCE ROW LEVEL SECURITY')
    op.execute(
        'CREATE POLICY tenant_isolation ON "tenants" '
        f'USING (id = {tenant_setting}) WITH CHECK (id = {tenant_setting})'
    )
    op.execute('REVOKE UPDATE, DELETE ON "audit_entries" FROM PUBLIC')
    op.execute(
        "CREATE FUNCTION reject_audit_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION 'audit_entries are append-only'; END; "
        "$$ LANGUAGE plpgsql"
    )
    op.execute(
        'CREATE TRIGGER audit_entries_append_only BEFORE UPDATE OR DELETE '
        'ON "audit_entries" FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation()'
    )
